import "./globals.css";
import { Orbit } from "next/font/google";

const orbit = Orbit({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={orbit.className}>{children}</body>
    </html>
  );
}
